### ISSUE TITLE
 Error: Unkown Pullpoint (onvif error code:SOAP-ENV:Sender->ter:ResourceUnknownFault）

### ISSUE THREAD

**Issue by wjcroom** [eyetowers/gonvif#1]
this cmd     events stream-events。
return this error。
Error: Unkown Pullpoint (onvif error code:SOAP-ENV:Sender->ter:ResourceUnknownFault）
run  gonvif  events   create-pull-point-subscription . can return the pullpoint refer url.
-point-subscription
{
  "SubscriptionReference": {
    "Address": "http://192.168.2.5:80/onvif/events/sub_pull_session_2"
  },
  "CurrentTime": {},
  "TerminationTime": {}
}

  use this url to  run gonvif   subcription pull-messages  -s  referusrl   
 return the same error .

-point-subscription
{
  "SubscriptionReference": {
    "Address": "http://192.168.2.5:80/onvif/events/sub_pull_session_2"
  },
  "CurrentTime": {},
  "TerminationTime": {}
use onvif device manager  https://github.com/aleksandrm8/ONVIF-Device-Manager can get event
only setting   only pullpoint   not setting  base suscription.

so what is wrong in the  gonvif  events  ?

I am reading the source code and try to fix this bug.

**Comment by wjcroom** [comment]
-capabilities
{
  "Capabilities": {
    "WSSubscriptionPolicySupport": true,
    "WSPullPointSupport": true,
    "MaxNotificationProducers": 32,
    "MaxPullPoints": 8
  }
}
properties
{
  "TopicNamespaceLocation": [
    "http://www.onvif.org/onvif/ver10/topics/topicns.xml"
  ],
  "FixedTopicSet": true,
  "TopicSet": {},
  "TopicExpressionDialect": [
    "http://docs.oasis-open.org/wsn/t-1/TopicExpression/Concrete",
    "http://www.onvif.org/ver10/tev/topicExpression/ConcreteSet"
  ],
  "MessageContentFilterDialect": [
    "http://www.onvif.org/ver10/tev/messageContentFilter/ItemFilter"
  ],
  "MessageContentSchemaLocation": [
    "http://www.onvif.org/onvif/ver10/schema/onvif.xsd"
  ]
}

https://github.com/aleksandrm8/ONVIF-Device-Manager   can get event

**Comment by wjcroom** [comment]
/* This method returns a PullPointSubscription that can be polled using PullMessages.
	This message contains the same elements as the SubscriptionRequest of the WS-BaseNotification without the ConsumerReference.
the createsucription:  use WS-BaseNotification.
 my cam only use PullPoint  . not use BaseNotification .maybe

**Comment by osery** [comment]
Hi, can you try running with `-v` and pasting the whole output including the raw xml messages? Thank you.

**Comment by osery** [comment]
@wjcroom I pushed a few fixes regarding event streaming. Can you try again with `v0.0.25`?

**Comment by wjcroom** [comment]
I try the 0.026, it's work fine, use./gonvif events stream-events
but a new error show 
Error: parsing time "2023-06-01T02:34:23" as "2006-01-02T15:04:05Z07:00": cannot parse "" as "Z07:00"

guess some date farmate have a 'Z' beturn date and time.

**Comment by wjcroom** [comment]
2023/06/01 02:34:24 --> POST http://192.168.2.8:7005/onvif/events/sub_pull_session_1
2023/06/01 02:34:24 BODY:
<Envelope xmlns="http://www.w3.org/2003/05/soap-envelope"><Header xmlns="http://www.w3.org/2003/05/soap-envelope"><ReplyTo xmlns="http://www.w3.org/2005/08/addressing"><Address xmlns="http://www.w3.org/2005/08/addressing">http://www.w3.org/2005/08/addressing/anonymous</Address></ReplyTo><To xmlns="http://www.w3.org/2005/08/addressing">http://192.168.2.5:80/onvif/events/sub_pull_session_1</To><Security xmlns="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"><UsernameToken><Username>admin</Username><Password Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordDigest">Ac17TEs6rDljXkUhAcJVaaVDjgE=</Password><Nonce EncodingType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#Base64Binary">arbvrsw5lg6m119coq4oas7c23vp1t3m</Nonce><Created xmlns="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">2023-06-01T02:34:24Z</Created></UsernameToken></Security></Header><Body xmlns="http://www.w3.org/2003/05/soap-envelope"><PullMessages xmlns="http://www.onvif.org/ver10/events/wsdl"><Timeout>PT60S</Timeout><MessageLimit>100</MessageLimit></PullMessages></Body></Envelope>
2023/06/01 02:34:25 <-- 200 http://192.168.2.8:7005/onvif/events/sub_pull_session_1
2023/06/01 02:34:25 BODY:
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://www.w3.org/2003/05/soap-envelope" xmlns:SOAP-ENC="http://www.w3.org/2003/05/soap-encoding" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:chan="http://schemas.microsoft.com/ws/2005/02/duplex" xmlns:wsa5="http://www.w3.org/2005/08/addressing" xmlns:wsadis="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:c14n="http://www.w3.org/2001/10/xml-exc-c14n#" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:saml1="urn:oasis:names:tc:SAML:1.0:assertion" xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:xenc="http://www.w3.org/2001/04/xmlenc#" xmlns:wsc="http://docs.oasis-open.org/ws-sx/ws-secureconversation/200512" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:xmime="http://tempuri.org/xmime.xsd" xmlns:xop="http://www.w3.org/2004/08/xop/include" xmlns:ttr="http://www.onvif.org/ver20/analytics/radiometry" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:tt="http://www.onvif.org/ver10/schema" xmlns:wsrfbf="http://docs.oasis-open.org/wsrf/bf-2" xmlns:wstop="http://docs.oasis-open.org/wsn/t-1" xmlns:wsrfr="http://docs.oasis-open.org/wsrf/r-2" xmlns:dn="http://www.onvif.org/ver10/network/wsdl" xmlns:d="http://schemas.xmlsoap.org/ws/2005/04/discovery" xmlns:tan="http://www.onvif.org/ver20/analytics/wsdl" xmlns:tand="http://www.onvif.org/ver10/analyticsdevice/wsdl" xmlns:tdisp="http://www.onvif.org/ver10/display/wsdl" xmlns:tds="http://www.onvif.org/ver10/device/wsdl" xmlns:tev="http://www.onvif.org/ver10/events/wsdl" xmlns:wsnt="http://docs.oasis-open.org/wsn/b-2" xmlns:timg20="http://www.onvif.org/ver20/imaging/wsdl" xmlns:tmd="http://www.onvif.org/ver10/deviceIO/wsdl" xmlns:tptz20="http://www.onvif.org/ver20/ptz/wsdl" xmlns:trc="http://www.onvif.org/ver10/recording/wsdl" xmlns:trp="http://www.onvif.org/ver10/replay/wsdl" xmlns:trt="http://www.onvif.org/ver10/media/wsdl" xmlns:trt20="http://www.onvif.org/ver20/media/wsdl" xmlns:tse="http://www.onvif.org/ver10/search/wsdl" xmlns:tns1="http://www.onvif.org/ver10/topics" xmlns:tnshik="http://www.hikvision.com/2011/event/topics" xmlns:ter="http://www.onvif.org/ver10/error"><SOAP-ENV:Header><wsa5:ReplyTo SOAP-ENV:mustUnderstand="true"><wsa5:Address>http://www.w3.org/2005/08/addressing/anonymous</wsa5:Address></wsa5:ReplyTo><wsa5:To SOAP-ENV:mustUnderstand="true">http://192.168.2.5:80/onvif/events/sub_pull_session_1</wsa5:To><wsa5:Action SOAP-ENV:mustUnderstand="true">http://www.onvif.org/ver10/events/wsdl/PullPointSubscription/PullMessagesResponse</wsa5:Action></SOAP-ENV:Header><SOAP-ENV:Body><tev:PullMessagesResponse><tev:CurrentTime>2023-06-01T02:34:24Z</tev:CurrentTime><tev:TerminationTime>2023-06-01T02:36:24Z</tev:TerminationTime><wsnt:NotificationMessage><wsnt:Topic Dialect="http://www.onvif.org/ver10/tev/topicExpression/ConcreteSet">tns1:VideoSource/MotionAlarm</wsnt:Topic><wsnt:Message><tt:Message UtcTime="2023-06-01T02:34:23" PropertyOperation="Initialized"><tt:Source><tt:SimpleItem
Name="Source" Value="vstoken_ch0001" /></tt:Source><tt:Data><tt:SimpleItem
Name="State" Value="false" /></tt:Data></tt:Message>
</wsnt:Message></wsnt:NotificationMessage><wsnt:NotificationMessage><wsnt:Topic Dialect="http://www.onvif.org/ver10/tev/topicExpression/ConcreteSet">tns1:RuleEngine/CellMotionDetector/Motion</wsnt:Topic><wsnt:Message><tt:Message UtcTime="2023-06-01T02:34:23" PropertyOperation="Initialized"><tt:Source><tt:SimpleItem
Name="VideoSourceConfigurationToken" Value="vsctoken_ch0001" /><tt:SimpleItem
Name="VideoAnalyticsConfigurationToken" Value="VideoAnalyticsToken" /><tt:SimpleItem
Name="Rule" Value="MyMotionDetectorRule" /></tt:Source><tt:Data><tt:SimpleItem
Name="IsMotion" Value="false" /></tt:Data></tt:Message>
</wsnt:Message></wsnt:NotificationMessage><wsnt:NotificationMessage><wsnt:Topic Dialect="http://www.onvif.org/ver10/tev/topicExpression/ConcreteSet">tns1:VideoSource</wsnt:Topic><wsnt:Message><tt:Message UtcTime="2023-06-01T02:34:23" PropertyOperation="Initialized"><tt:Source><tt:SimpleItem
Name="Source" Value="vstoken_ch0001" /></tt:Source><tt:Data><tt:SimpleItem
Name="State" Value="FALSE" /></tt:Data></tt:Message>
</wsnt:Message></wsnt:NotificationMessage><wsnt:NotificationMessage><wsnt:Topic Dialect="http://www.onvif.org/ver10/tev/topicExpression/ConcreteSet">tns1:VideoAnalytics/tnshik:MotionAlarm</wsnt:Topic><wsnt:Message><tt:Message UtcTime="2023-06-01T02:34:23" PropertyOperation="Initialized"><tt:Source><tt:SimpleItem
Name="Source" Value="vstoken_ch0001" /></tt:Source><tt:Data><tt:SimpleItem
Name="State" Value="FALSE" /></tt:Data></tt:Message>
</wsnt:Message></wsnt:NotificationMessage><wsnt:NotificationMessage><wsnt:Topic Dialect="http://www.onvif.org/ver10/tev/topicExpression/ConcreteSet">tns1:UserAlarm/VideoCover</wsnt:Topic><wsnt:Message><tt:Message UtcTime="2023-06-01T02:34:23" PropertyOperation="Initialized"><tt:Source><tt:SimpleItem
Name="VideoSourceToken" Value="vstoken_ch0001" /></tt:Source><tt:Data><tt:SimpleItem
Name="State" Value="FALSE" /></tt:Data></tt:Message>
</wsnt:Message></wsnt:NotificationMessage><wsnt:NotificationMessage><wsnt:Topic Dialect="http://www.onvif.org/ver10/tev/topicExpression/ConcreteSet">tns1:RuleEngine/TamperDetector/Tamper</wsnt:Topic><wsnt:Message><tt:Message UtcTime="2023-06-01T02:34:23" PropertyOperation="Initialized"><tt:Source><tt:SimpleItem
Name="VideoSourceToken" Value="vstoken_ch0001" /></tt:Source><tt:Data><tt:SimpleItem
Name="State" Value="FALSE" /></tt:Data></tt:Message>
</wsnt:Message></wsnt:NotificationMessage><wsnt:NotificationMessage><wsnt:Topic Dialect="http://www.onvif.org/ver10/tev/topicExpression/ConcreteSet">tns1:Device/Trigger/DigitalInput</wsnt:Topic><wsnt:Message><tt:Message UtcTime="2023-06-01T02:34:23" PropertyOperation="Initialized"><tt:Source><tt:SimpleItem
Name="InputToken" Value="AlarmIn_0001" /></tt:Source><tt:Data><tt:SimpleItem
Name="LogicalState" Value="true" /></tt:Data></tt:Message>
</wsnt:Message></wsnt:NotificationMessage><wsnt:NotificationMessage><wsnt:Topic Dialect="http://www.onvif.org/ver10/tev/topicExpression/ConcreteSet">tns1:Device/Trigger/AlarmIn</wsnt:Topic><wsnt:Message><tt:Message UtcTime="2023-06-01T02:34:23" PropertyOperation="Initialized"><tt:Source><tt:SimpleItem
Name="AlarmInToken" Value="AlarmIn_0001" /></tt:Source><tt:Data><tt:SimpleItem
Name="State" Value="TRUE" /></tt:Data></tt:Message>
</wsnt:Message></wsnt:NotificationMessage><wsnt:NotificationMessage><wsnt:Topic Dialect="http://www.onvif.org/ver10/tev/topicExpression/ConcreteSet">tns1:Device/Trigger/DigitalInput</wsnt:Topic><wsnt:Message><tt:Message UtcTime="2023-06-01T02:34:23" PropertyOperation="Initialized"><tt:Source><tt:SimpleItem
Name="InputToken" Value="AlarmIn_0002" /></tt:Source><tt:Data><tt:SimpleItem
Name="LogicalState" Value="false" /></tt:Data></tt:Message>
</wsnt:Message></wsnt:NotificationMessage><wsnt:NotificationMessage><wsnt:Topic Dialect="http://www.onvif.org/ver10/tev/topicExpression/ConcreteSet">tns1:Device/Trigger/AlarmIn</wsnt:Topic><wsnt:Message><tt:Message UtcTime="2023-06-01T02:34:23" PropertyOperation="Initialized"><tt:Source><tt:SimpleItem
Name="AlarmInToken" Value="AlarmIn_0002" /></tt:Source><tt:Data><tt:SimpleItem
Name="State" Value="FALSE" /></tt:Data></tt:Message>
</wsnt:Message></wsnt:NotificationMessage></tev:PullMessagesResponse></SOAP-ENV:Body></SOAP-ENV:Envelope>
2023/06/01 02:34:25 --> POST http://192.168.2.8:7005/onvif/events/sub_pull_session_1
2023/06/01 02:34:25 BODY:
<Envelope xmlns="http://www.w3.org/2003/05/soap-envelope"><Header xmlns="http://www.w3.org/2003/05/soap-envelope"><ReplyTo xmlns="http://www.w3.org/2005/08/addressing"><Address xmlns="http://www.w3.org/2005/08/addressing">http://www.w3.org/2005/08/addressing/anonymous</Address></ReplyTo><To xmlns="http://www.w3.org/2005/08/addressing">http://192.168.2.5:80/onvif/events/sub_pull_session_1</To><Security xmlns="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"><UsernameToken><Username>admin</Username><Password Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordDigest">zy3L8wxgXyuTqUlIMTE3OdzYYoE=</Password><Nonce EncodingType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#Base64Binary">y9zwxwvnoqx3aa579ksil89nuwyypiry</Nonce><Created xmlns="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">2023-06-01T02:34:25Z</Created></UsernameToken></Security></Header><Body xmlns="http://www.w3.org/2003/05/soap-envelope"><Content></Content></Body></Envelope>
2023/06/01 02:34:26 <-- 400 http://192.168.2.8:7005/onvif/events/sub_pull_session_1
2023/06/01 02:34:26 BODY:
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://www.w3.org/2003/05/soap-envelope" xmlns:SOAP-ENC="http://www.w3.org/2003/05/soap-encoding" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:chan="http://schemas.microsoft.com/ws/2005/02/duplex" xmlns:wsa5="http://www.w3.org/2005/08/addressing" xmlns:wsadis="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:c14n="http://www.w3.org/2001/10/xml-exc-c14n#" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:saml1="urn:oasis:names:tc:SAML:1.0:assertion" xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:xenc="http://www.w3.org/2001/04/xmlenc#" xmlns:wsc="http://docs.oasis-open.org/ws-sx/ws-secureconversation/200512" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:xmime="http://tempuri.org/xmime.xsd" xmlns:xop="http://www.w3.org/2004/08/xop/include" xmlns:ttr="http://www.onvif.org/ver20/analytics/radiometry" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:tt="http://www.onvif.org/ver10/schema" xmlns:wsrfbf="http://docs.oasis-open.org/wsrf/bf-2" xmlns:wstop="http://docs.oasis-open.org/wsn/t-1" xmlns:wsrfr="http://docs.oasis-open.org/wsrf/r-2" xmlns:dn="http://www.onvif.org/ver10/network/wsdl" xmlns:d="http://schemas.xmlsoap.org/ws/2005/04/discovery" xmlns:tan="http://www.onvif.org/ver20/analytics/wsdl" xmlns:tand="http://www.onvif.org/ver10/analyticsdevice/wsdl" xmlns:tdisp="http://www.onvif.org/ver10/display/wsdl" xmlns:tds="http://www.onvif.org/ver10/device/wsdl" xmlns:tev="http://www.onvif.org/ver10/events/wsdl" xmlns:wsnt="http://docs.oasis-open.org/wsn/b-2" xmlns:timg20="http://www.onvif.org/ver20/imaging/wsdl" xmlns:tmd="http://www.onvif.org/ver10/deviceIO/wsdl" xmlns:tptz20="http://www.onvif.org/ver20/ptz/wsdl" xmlns:trc="http://www.onvif.org/ver10/recording/wsdl" xmlns:trp="http://www.onvif.org/ver10/replay/wsdl" xmlns:trt="http://www.onvif.org/ver10/media/wsdl" xmlns:trt20="http://www.onvif.org/ver20/media/wsdl" xmlns:tse="http://www.onvif.org/ver10/search/wsdl" xmlns:tns1="http://www.onvif.org/ver10/topics" xmlns:tnshik="http://www.hikvision.com/2011/event/topics" xmlns:ter="http://www.onvif.org/ver10/error"><SOAP-ENV:Body><SOAP-ENV:Fault><SOAP-ENV:Code><SOAP-ENV:Value>SOAP-ENV:Sender</SOAP-ENV:Value></SOAP-ENV:Code><SOAP-ENV:Reason><SOAP-ENV:Text xml:lang="en">Method 'Content' not implemented: method name or namespace not recognized</SOAP-ENV:Text></SOAP-ENV:Reason></SOAP-ENV:Fault></SOAP-ENV:Body></SOAP-ENV:Envelope>
Error: parsing time "2023-06-01T02:34:23" as "2006-01-02T15:04:05Z07:00": cannot parse "" as "Z07:00"

this is part of return with -v

**Comment by wjcroom** [comment]
好吧，在打包，拆包过程中，由于时间格式不对，出现了错误，导致了订阅失败。

**Comment by wjcroom** [comment]
2023/06/01 02:34:24 --> POST [http://192.168.2.8:7005/on](http://192.168.2.8:7005/onvif/events/sub_pull_session_1)

the port 7005,is the wan port -
cam in the lan  cam port is 80.

i use the wanport  wanip:7005 to   lan,cam.  laniP:80
so on 0.0.24 govif, ,the reply . subcrition src must replaced with wanip:7005.
maybe you have fix that .

.

**Comment by wjcroom** [comment]
POST http://192.168.2.8:7005/onvif/events/sub_pull_session_1
first post  status is 200 。
but reply cotment [，“](tt:Message UtcTime="2023-06-01T02:34:23")”  is not parsing，have a error

the second post status 400
so events stream-events  still not work。

**Comment by wjcroom** [comment]
我看了一下代码，第一次对话，验证通过，第二次失败，可能的原因是使用的digest auth。密码是随机的吧。在时间格式解析出错外，可能还有验证登陆待修正。
我正在查找解析时间的出错位置，有可能会找到

**Comment by wjcroom** [comment]
post   <Content></Content>
return  400  and error code   message is<SOAP-ENV:Text xml:lang="en">Method 'Content' not implemented: method name or namespace not recognized</SOAP-ENV:Text>
看来不是验证出的问题，是在pullmessage成功以后，又发送的一个Contend soap 这是要取得一个什么内容呢？虽然请求了，但是摄像头没有实现这个方法。
时间解析，应该是在return service.PullMessagesContext(
		context.Background(),
		request,
这里出的错，在xml处理过程中。

**Comment by wjcroom** [comment]
// CallContext performs HTTP POST request with a context
func (s *Client) CallContext(ctx context.Context, soapAction string, request, response interface{}) error {
	return s.call(ctx, soapAction, request, response, nil, nil)
}

// Call performs HTTP POST request.
// Note that if the server returns a status code >= 400, a HTTPError will be returned

  in gowsdl/soap/client.go

an other   with -v 

after  create_subscription-------------------------------------------
add get a rspt.subscrption url.  http://192.168.2.5:80/onvif/events/sub_pull_session_1
the  events stream-events funtion    request s:

2023/06/01 07:27:22 --> POST http://192.168.2.8:7005/onvif/events/sub_pull_session_1
2023/06/01 07:27:22 BODY:
<Envelope xmlns="http://www.w3.org/2003/05/soap-envelope"><Header xmlns="http://www.w3.org/2003/05/soap-envelope"><ReplyTo xmlns="http://www.w3.org/2005/08/addressing"><Address xmlns="http://www.w3.org/2005/08/addressing">http://www.w3.org/2005/08/addressing/anonymous</Address></ReplyTo><To xmlns="http://www.w3.org/2005/08/addressing">http://192.168.2.5:80/onvif/events/sub_pull_session_1</To><Security xmlns="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"><UsernameToken><Username>admin</Username><Password Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordDigest">Da1Bqq1QfVTTmBY09bZUOmy3J2U=</Password><Nonce EncodingType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#Base64Binary">khnograluhi807fliwu6vbv24sctxmmo</Nonce><Created xmlns="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">2023-06-01T07:27:22Z</Created></UsernameToken></Security></Header><Body xmlns="http://www.w3.org/2003/05/soap-envelope"><PullMessages xmlns="http://www.onvif.org/ver10/events/wsdl"><Timeout>PT60S</Timeout><MessageLimit>100</MessageLimit></PullMessages></Body></Envelope>
2023/06/01 07:27:23 <-- 200 http://192.168.2.8:7005/onvif/events/sub_pull_session_1
2023/06/01 07:27:23 BODY:
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://www.w3.org/2003/05/soap-envelope" xmlns:SOAP-ENC="http://www.w3.org/2003/05/soap-encoding" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:chan="http://schemas.microsoft.com/ws/2005/02/duplex" xmlns:wsa5="http://www.w3.org/2005/08/addressing" xmlns:wsadis="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:c14n="http://www.w3.org/2001/10/xml-exc-c14n#" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:saml1="urn:oasis:names:tc:SAML:1.0:assertion" xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:xenc="http://www.w3.org/2001/04/xmlenc#" xmlns:wsc="http://docs.oasis-open.org/ws-sx/ws-secureconversation/200512" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:xmime="http://tempuri.org/xmime.xsd" xmlns:xop="http://www.w3.org/2004/08/xop/include" xmlns:ttr="http://www.onvif.org/ver20/analytics/radiometry" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:tt="http://www.onvif.org/ver10/schema" xmlns:wsrfbf="http://docs.oasis-open.org/wsrf/bf-2" xmlns:wstop="http://docs.oasis-open.org/wsn/t-1" xmlns:wsrfr="http://docs.oasis-open.org/wsrf/r-2" xmlns:dn="http://www.onvif.org/ver10/network/wsdl" xmlns:d="http://schemas.xmlsoap.org/ws/2005/04/discovery" xmlns:tan="http://www.onvif.org/ver20/analytics/wsdl" xmlns:tand="http://www.onvif.org/ver10/analyticsdevice/wsdl" xmlns:tdisp="http://www.onvif.org/ver10/display/wsdl" xmlns:tds="http://www.onvif.org/ver10/device/wsdl" xmlns:tev="http://www.onvif.org/ver10/events/wsdl" xmlns:wsnt="http://docs.oasis-open.org/wsn/b-2" xmlns:timg20="http://www.onvif.org/ver20/imaging/wsdl" xmlns:tmd="http://www.onvif.org/ver10/deviceIO/wsdl" xmlns:tptz20="http://www.onvif.org/ver20/ptz/wsdl" xmlns:trc="http://www.onvif.org/ver10/recording/wsdl" xmlns:trp="http://www.onvif.org/ver10/replay/wsdl" xmlns:trt="http://www.onvif.org/ver10/media/wsdl" xmlns:trt20="http://www.onvif.org/ver20/media/wsdl" xmlns:tse="http://www.onvif.org/ver10/search/wsdl" xmlns:tns1="http://www.onvif.org/ver10/topics" xmlns:tnshik="http://www.hikvision.com/2011/event/topics" xmlns:ter="http://www.onvif.org/ver10/error"><SOAP-ENV:Header><wsa5:ReplyTo SOAP-ENV:mustUnderstand="true"><wsa5:Address>http://www.w3.org/2005/08/addressing/anonymous</wsa5:Address></wsa5:ReplyTo><wsa5:To SOAP-ENV:mustUnderstand="true">http://192.168.2.5:80/onvif/events/sub_pull_session_1</wsa5:To><wsa5:Action SOAP-ENV:mustUnderstand="true">http://www.onvif.org/ver10/events/wsdl/PullPointSubscription/PullMessagesResponse</wsa5:Action></SOAP-ENV:Header><SOAP-ENV:Body><tev:PullMessagesResponse><tev:CurrentTime>2023-06-01T07:27:22Z</tev:CurrentTime><tev:TerminationTime>2023-06-01T07:29:22Z</tev:TerminationTime><wsnt:NotificationMessage><wsnt:Topic Dialect="http://www.onvif.org/ver10/tev/topicExpression/ConcreteSet">tns1:VideoSource/MotionAlarm</wsnt:Topic><wsnt:Message><tt:Message UtcTime="2023-06-01T07:27:22" PropertyOperation="Initialized"><tt:Source><tt:SimpleItem
Name="Source" Value="vstoken_ch0001" /></tt:Source><tt:Data><tt:SimpleItem
Name="State" Value="false" /></tt:Data></tt:Message>
</wsnt:Message></wsnt:NotificationMessage><wsnt:NotificationMessage><wsnt:Topic Dialect="http://www.onvif.org/ver10/tev/topicExpression/ConcreteSet">tns1:RuleEngine/CellMotionDetector/Motion</wsnt:Topic><wsnt:Message><tt:Message UtcTime="2023-06-01T07:27:22" PropertyOperation="Initialized"><tt:Source><tt:SimpleItem
Name="VideoSourceConfigurationToken" Value="vsctoken_ch0001" /><tt:SimpleItem
Name="VideoAnalyticsConfigurationToken" Value="VideoAnalyticsToken" /><tt:SimpleItem
Name="Rule" Value="MyMotionDetectorRule" /></tt:Source><tt:Data><tt:SimpleItem
Name="IsMotion" Value="false" /></tt:Data></tt:Message>
</wsnt:Message></wsnt:NotificationMessage><wsnt:NotificationMessage><wsnt:Topic Dialect="http://www.onvif.org/ver10/tev/topicExpression/ConcreteSet">tns1:VideoSource</wsnt:Topic><wsnt:Message><tt:Message UtcTime="2023-06-01T07:27:22" PropertyOperation="Initialized"><tt:Source><tt:SimpleItem
Name="Source" Value="vstoken_ch0001" /></tt:Source><tt:Data><tt:SimpleItem
Name="State" Value="FALSE" /></tt:Data></tt:Message>
</wsnt:Message></wsnt:NotificationMessage><wsnt:NotificationMessage><wsnt:Topic Dialect="http://www.onvif.org/ver10/tev/topicExpression/ConcreteSet">tns1:VideoAnalytics/tnshik:MotionAlarm</wsnt:Topic><wsnt:Message><tt:Message UtcTime="2023-06-01T07:27:22" PropertyOperation="Initialized"><tt:Source><tt:SimpleItem
Name="Source" Value="vstoken_ch0001" /></tt:Source><tt:Data><tt:SimpleItem
Name="State" Value="FALSE" /></tt:Data></tt:Message>
</wsnt:Message></wsnt:NotificationMessage><wsnt:NotificationMessage><wsnt:Topic Dialect="http://www.onvif.org/ver10/tev/topicExpression/ConcreteSet">tns1:UserAlarm/VideoCover</wsnt:Topic><wsnt:Message><tt:Message UtcTime="2023-06-01T07:27:22" PropertyOperation="Initialized"><tt:Source><tt:SimpleItem
Name="VideoSourceToken" Value="vstoken_ch0001" /></tt:Source><tt:Data><tt:SimpleItem
Name="State" Value="FALSE" /></tt:Data></tt:Message>
</wsnt:Message></wsnt:NotificationMessage><wsnt:NotificationMessage><wsnt:Topic Dialect="http://www.onvif.org/ver10/tev/topicExpression/ConcreteSet">tns1:RuleEngine/TamperDetector/Tamper</wsnt:Topic><wsnt:Message><tt:Message UtcTime="2023-06-01T07:27:22" PropertyOperation="Initialized"><tt:Source><tt:SimpleItem
Name="VideoSourceToken" Value="vstoken_ch0001" /></tt:Source><tt:Data><tt:SimpleItem
Name="State" Value="FALSE" /></tt:Data></tt:Message>
</wsnt:Message></wsnt:NotificationMessage><wsnt:NotificationMessage><wsnt:Topic Dialect="http://www.onvif.org/ver10/tev/topicExpression/ConcreteSet">tns1:Device/Trigger/DigitalInput</wsnt:Topic><wsnt:Message><tt:Message UtcTime="2023-06-01T07:27:22" PropertyOperation="Initialized"><tt:Source><tt:SimpleItem
Name="InputToken" Value="AlarmIn_0001" /></tt:Source><tt:Data><tt:SimpleItem
Name="LogicalState" Value="true" /></tt:Data></tt:Message>
</wsnt:Message></wsnt:NotificationMessage><wsnt:NotificationMessage><wsnt:Topic Dialect="http://www.onvif.org/ver10/tev/topicExpression/ConcreteSet">tns1:Device/Trigger/AlarmIn</wsnt:Topic><wsnt:Message><tt:Message UtcTime="2023-06-01T07:27:22" PropertyOperation="Initialized"><tt:Source><tt:SimpleItem
Name="AlarmInToken" Value="AlarmIn_0001" /></tt:Source><tt:Data><tt:SimpleItem
Name="State" Value="TRUE" /></tt:Data></tt:Message>
</wsnt:Message></wsnt:NotificationMessage><wsnt:NotificationMessage><wsnt:Topic Dialect="http://www.onvif.org/ver10/tev/topicExpression/ConcreteSet">tns1:Device/Trigger/DigitalInput</wsnt:Topic><wsnt:Message><tt:Message UtcTime="2023-06-01T07:27:22" PropertyOperation="Initialized"><tt:Source><tt:SimpleItem
Name="InputToken" Value="AlarmIn_0002" /></tt:Source><tt:Data><tt:SimpleItem
Name="LogicalState" Value="false" /></tt:Data></tt:Message>
</wsnt:Message></wsnt:NotificationMessage><wsnt:NotificationMessage><wsnt:Topic Dialect="http://www.onvif.org/ver10/tev/topicExpression/ConcreteSet">tns1:Device/Trigger/AlarmIn</wsnt:Topic><wsnt:Message><tt:Message UtcTime="2023-06-01T07:27:22" PropertyOperation="Initialized"><tt:Source><tt:SimpleItem
Name="AlarmInToken" Value="AlarmIn_0002" /></tt:Source><tt:Data><tt:SimpleItem
Name="State" Value="FALSE" /></tt:Data></tt:Message>
</wsnt:Message></wsnt:NotificationMessage></tev:PullMessagesResponse></SOAP-ENV:Body></SOAP-ENV:Envelope>

 2023/06/01 07:27:23 --> POST http://192.168.2.8:7005/onvif/events/sub_pull_session_1
2023/06/01 07:27:23 BODY:
<Envelope xmlns="http://www.w3.org/2003/05/soap-envelope"><Header xmlns="http://www.w3.org/2003/05/soap-envelope"><ReplyTo xmlns="http://www.w3.org/2005/08/addressing"><Address xmlns="http://www.w3.org/2005/08/addressing">http://www.w3.org/2005/08/addressing/anonymous</Address></ReplyTo><To xmlns="http://www.w3.org/2005/08/addressing">http://192.168.2.5:80/onvif/events/sub_pull_session_1</To><Security xmlns="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"><UsernameToken><Username>admin</Username><Password Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordDigest">d+fA/TNDwJrPf6cnrl6PoGdohXw=</Password><Nonce EncodingType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#Base64Binary">lf3jhmaw9lkttg87wmqjpmxuv0cftmlm</Nonce><Created xmlns="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd">2023-06-01T07:27:23Z</Created></UsernameToken></Security></Header><Body xmlns="http://www.w3.org/2003/05/soap-envelope"><Content></Content></Body></Envelope>
2023/06/01 07:27:23 <-- 400 http://192.168.2.8:7005/onvif/events/sub_pull_session_1
2023/06/01 07:27:23 BODY:
<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://www.w3.org/2003/05/soap-envelope" xmlns:SOAP-ENC="http://www.w3.org/2003/05/soap-encoding" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:chan="http://schemas.microsoft.com/ws/2005/02/duplex" xmlns:wsa5="http://www.w3.org/2005/08/addressing" xmlns:wsadis="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:c14n="http://www.w3.org/2001/10/xml-exc-c14n#" xmlns:ds="http://www.w3.org/2000/09/xmldsig#" xmlns:saml1="urn:oasis:names:tc:SAML:1.0:assertion" xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd" xmlns:xenc="http://www.w3.org/2001/04/xmlenc#" xmlns:wsc="http://docs.oasis-open.org/ws-sx/ws-secureconversation/200512" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:xmime="http://tempuri.org/xmime.xsd" xmlns:xop="http://www.w3.org/2004/08/xop/include" xmlns:ttr="http://www.onvif.org/ver20/analytics/radiometry" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:tt="http://www.onvif.org/ver10/schema" xmlns:wsrfbf="http://docs.oasis-open.org/wsrf/bf-2" xmlns:wstop="http://docs.oasis-open.org/wsn/t-1" xmlns:wsrfr="http://docs.oasis-open.org/wsrf/r-2" xmlns:dn="http://www.onvif.org/ver10/network/wsdl" xmlns:d="http://schemas.xmlsoap.org/ws/2005/04/discovery" xmlns:tan="http://www.onvif.org/ver20/analytics/wsdl" xmlns:tand="http://www.onvif.org/ver10/analyticsdevice/wsdl" xmlns:tdisp="http://www.onvif.org/ver10/display/wsdl" xmlns:tds="http://www.onvif.org/ver10/device/wsdl" xmlns:tev="http://www.onvif.org/ver10/events/wsdl" xmlns:wsnt="http://docs.oasis-open.org/wsn/b-2" xmlns:timg20="http://www.onvif.org/ver20/imaging/wsdl" xmlns:tmd="http://www.onvif.org/ver10/deviceIO/wsdl" xmlns:tptz20="http://www.onvif.org/ver20/ptz/wsdl" xmlns:trc="http://www.onvif.org/ver10/recording/wsdl" xmlns:trp="http://www.onvif.org/ver10/replay/wsdl" xmlns:trt="http://www.onvif.org/ver10/media/wsdl" xmlns:trt20="http://www.onvif.org/ver20/media/wsdl" xmlns:tse="http://www.onvif.org/ver10/search/wsdl" xmlns:tns1="http://www.onvif.org/ver10/topics" xmlns:tnshik="http://www.hikvision.com/2011/event/topics" xmlns:ter="http://www.onvif.org/ver10/error"><SOAP-ENV:Body><SOAP-ENV:Fault><SOAP-ENV:Code><SOAP-ENV:Value>SOAP-ENV:Sender</SOAP-ENV:Value></SOAP-ENV:Code><SOAP-ENV:Reason><SOAP-ENV:Text xml:lang="en">Method 'Content' not implemented: method name or namespace not recognized</SOAP-ENV:Text></SOAP-ENV:Reason></SOAP-ENV:Fault></SOAP-ENV:Body></SOAP-ENV:Envelope>
Error: parsing time "2023-06-01T07:27:22" as "2006-01-02T15:04:05Z07:00": cannot parse "" as "Z07:00"

**Comment by osery** [comment]
Hi @wjcroom, I think `v0.0.27` should fix the date-time parsing issue. As to the port, I think that should already be done automatically. Am I missing something?

**Comment by wjcroom** [comment]
i will try it


















At 2023-06-02 19:56:05, "Ondrej Sery" ***@***.***> wrote:

Hi @wjcroom, I think v0.0.27 should fix the date-time parsing issue. As to the port, I think that should already be done automatically. Am I missing something?

**Comment by wjcroom** [comment]
Yes I get the events   ｒｅａｌ　 time。 json ， one by one 。 events  stream-events  cmd。

**Comment by wjcroom** [comment]
subscription pullmessages  　  still not work . while it will  read event once by once ?

**Comment by wjcroom** [comment]
hava fixed

**Comment by wjcroom** [comment]
may i add  args. to set event type. such as motion. alarm ....?
behind the stream-events

**Comment by osery** [comment]
> may i add args. to set event type. such as motion. alarm ....? behind the stream-events

Sure, PRs welcome. :v:
